"""Shared UID identities and request pacing. Credentials and mail bytes are never stored."""
import asyncio
import hashlib
import time
import uuid
from dataclasses import dataclass
import json
from datetime import datetime
from .models import Message
from contextlib import asynccontextmanager, contextmanager
from dataclasses import replace

import psycopg
from psycopg_pool import ConnectionPool
from .uid_store import MAX_UID, UIDStoreError

SCHEMA = '''
CREATE TABLE settings (name TEXT PRIMARY KEY, value BIGINT NOT NULL);
CREATE TABLE mailboxes (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 namespace TEXT NOT NULL, inbox TEXT NOT NULL, uidvalidity BIGINT NOT NULL CHECK(uidvalidity BETWEEN 1 AND 4294967295),
 next_uid BIGINT NOT NULL DEFAULT 1 CHECK(next_uid BETWEEN 1 AND 4294967295),
 revision BIGINT NOT NULL DEFAULT 0 CHECK(revision>=0), UNIQUE(namespace,inbox));
CREATE TABLE message_uids (mailbox_id BIGINT NOT NULL REFERENCES mailboxes(id), message_id TEXT NOT NULL,
 uid BIGINT NOT NULL CHECK(uid BETWEEN 1 AND 4294967295), active INTEGER NOT NULL CHECK(active IN (0,1)),
 recent INTEGER NOT NULL DEFAULT 1 CHECK(recent IN (0,1)), UNIQUE(mailbox_id,uid));
CREATE UNIQUE INDEX active_identity ON message_uids(mailbox_id,message_id) WHERE active=1;
CREATE TABLE request_budgets (credential_hash TEXT PRIMARY KEY,
 next_request TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
 cooldown_until TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp());
CREATE TABLE mailbox_leases (namespace TEXT NOT NULL,inbox TEXT NOT NULL,owner TEXT NOT NULL,fence BIGINT NOT NULL DEFAULT 1,expires_at TIMESTAMPTZ NOT NULL,PRIMARY KEY(namespace,inbox));
CREATE TABLE mailbox_snapshots (namespace TEXT NOT NULL, inbox TEXT NOT NULL, credential_hash TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(), payload JSONB NOT NULL, PRIMARY KEY(namespace,inbox,credential_hash));
INSERT INTO settings VALUES ('schema_version',2);
'''


def lock_key(namespace, inbox):
    value = hashlib.sha256((namespace+'\0'+inbox).encode()).digest()[:8]
    return int.from_bytes(value, 'big', signed=True)


@dataclass(frozen=True)
class MailboxLease:
    namespace: str
    inbox: str
    owner: str
    fence: int


class PostgresUIDStore:
    @classmethod
    def initialize(cls, dsn, *, uidvalidity=None):
        generation = int(time.time()) if uidvalidity is None else uidvalidity
        if not 0 < generation <= MAX_UID:
            raise UIDStoreError('Invalid UIDVALIDITY generation')
        try:
            with psycopg.connect(dsn, connect_timeout=10) as db:
                db.execute(SCHEMA)
                db.execute("INSERT INTO settings VALUES ('generation',%s)", (generation,))
        except psycopg.Error:
            raise UIDStoreError('PostgreSQL initialization failed; schema must be empty and reachable') from None
        return cls(dsn)

    def __init__(self, dsn):
        self.pool = ConnectionPool(dsn, min_size=1, max_size=12, timeout=15,
                                   kwargs={'connect_timeout':10}, open=False)
        try:
            self.pool.open(wait=True, timeout=15)
            with self._db() as db:
                if db.execute("SELECT value FROM settings WHERE name='schema_version'").fetchone() != (2,):
                    raise UIDStoreError('Unsupported UID database schema')
                generation = db.execute("SELECT value FROM settings WHERE name='generation'").fetchone()
                if not generation or not 0 < generation[0] <= MAX_UID:
                    raise UIDStoreError('Invalid UID generation')
                if db.execute('SELECT 1 FROM message_uids u JOIN mailboxes m ON m.id=u.mailbox_id WHERE u.uid>=m.next_uid LIMIT 1').fetchone():
                    raise UIDStoreError('Invalid UID counters')
        except Exception:
            self.pool.close()
            raise UIDStoreError('PostgreSQL UID database unavailable or invalid; explicit initialization or recovery required') from None

    @contextmanager
    def _db(self):
        try:
            with self.pool.connection() as db:
                yield db
        except UIDStoreError:
            raise
        except Exception:
            raise UIDStoreError('PostgreSQL UID operation failed') from None

    def _mailbox(self, db, namespace, inbox, *, create=False):
        if create:
            db.execute("INSERT INTO mailboxes(namespace,inbox,uidvalidity) SELECT %s,%s,value FROM settings WHERE name='generation' ON CONFLICT(namespace,inbox) DO NOTHING", (namespace,inbox))
        return db.execute('SELECT id,uidvalidity,next_uid,revision FROM mailboxes WHERE namespace=%s AND inbox=%s'+(' FOR UPDATE' if create else ''), (namespace,inbox)).fetchone()

    def active_ids(self, namespace, inbox):
        with self._db() as db:
            return {r[0] for r in db.execute('SELECT u.message_id FROM message_uids u JOIN mailboxes m ON m.id=u.mailbox_id WHERE namespace=%s AND inbox=%s AND active=1',(namespace,inbox))}

    def revision(self, namespace, inbox):
        with self._db() as db:
            m = self._mailbox(db,namespace,inbox)
            return m[3] if m else 0

    def reconcile(self, namespace, inbox, messages, *, confirmed_removed=(), expected_revision=None, lease=None):
        messages = list(messages)
        by_id = {m.message_id:m for m in messages}
        if len(by_id) != len(messages): raise UIDStoreError('Duplicate candidate message identities')
        confirmed = set(confirmed_removed)
        if confirmed & by_id.keys(): raise UIDStoreError('Conflicting candidate membership')
        with self._db() as db:
            self._check_lease(db,lease)
            mid,validity,next_uid,revision = self._mailbox(db,namespace,inbox,create=True)
            if expected_revision is not None and revision != expected_revision:
                raise UIDStoreError('Stale mailbox reconciliation; refresh again')
            mappings = dict(db.execute('SELECT message_id,uid FROM message_uids WHERE mailbox_id=%s AND active=1',(mid,)))
            missing = mappings.keys()-by_id.keys()
            if missing-confirmed: raise UIDStoreError('Missing identities require confirmed folder removal')
            changed = bool(missing)
            for identifier in missing:
                db.execute('UPDATE message_uids SET active=0,recent=0 WHERE mailbox_id=%s AND message_id=%s AND active=1',(mid,identifier))
            for message in sorted(messages,key=lambda m:(m.timestamp,m.message_id)):
                if message.message_id not in mappings:
                    if next_uid >= MAX_UID: raise UIDStoreError('UID space exhausted; deliberate recovery required')
                    db.execute('INSERT INTO message_uids VALUES (%s,%s,%s,1,1)',(mid,message.message_id,next_uid))
                    mappings[message.message_id] = next_uid
                    next_uid += 1
                    changed = True
            db.execute('UPDATE mailboxes SET next_uid=%s,revision=%s WHERE id=%s',(next_uid,revision+int(changed),mid))
            return validity,next_uid,sorted((replace(m,uid=mappings[m.message_id]) for m in messages),key=lambda m:m.uid)

    def claim_recent(self, namespace, inbox, *, readonly=False):
        with self._db() as db:
            m = db.execute('SELECT id FROM mailboxes WHERE namespace=%s AND inbox=%s FOR UPDATE',(namespace,inbox)).fetchone()
            if not m: return set()
            result = {r[0] for r in db.execute('SELECT uid FROM message_uids WHERE mailbox_id=%s AND active=1 AND recent=1',(m[0],))}
            if not readonly: db.execute('UPDATE message_uids SET recent=0 WHERE mailbox_id=%s AND active=1',(m[0],))
            return result

    def _try_lease(self, namespace, inbox, owner, seconds):
        with self._db() as db:
            row = db.execute("INSERT INTO mailbox_leases(namespace,inbox,owner,expires_at) VALUES (%s,%s,%s,clock_timestamp()+(%s * interval '1 second')) ON CONFLICT(namespace,inbox) DO UPDATE SET owner=excluded.owner,fence=mailbox_leases.fence+1,expires_at=excluded.expires_at WHERE mailbox_leases.expires_at<=clock_timestamp() RETURNING fence",(namespace,inbox,owner,seconds)).fetchone()
            return row[0] if row else None

    def _renew_lease(self, lease, seconds):
        with self._db() as db:
            return db.execute("UPDATE mailbox_leases SET expires_at=clock_timestamp()+(%s * interval '1 second') WHERE namespace=%s AND inbox=%s AND owner=%s AND fence=%s AND expires_at>clock_timestamp() RETURNING fence",(seconds,lease.namespace,lease.inbox,lease.owner,lease.fence)).fetchone() is not None

    def _release_lease(self, lease):
        with self._db() as db:
            db.execute('UPDATE mailbox_leases SET expires_at=clock_timestamp() WHERE namespace=%s AND inbox=%s AND owner=%s AND fence=%s',(lease.namespace,lease.inbox,lease.owner,lease.fence))

    def _check_lease(self, db, lease):
        if lease is None: return
        row = db.execute('SELECT fence FROM mailbox_leases WHERE namespace=%s AND inbox=%s AND owner=%s AND fence=%s AND expires_at>clock_timestamp() FOR UPDATE',(lease.namespace,lease.inbox,lease.owner,lease.fence)).fetchone()
        if not row: raise UIDStoreError('Mailbox coordination lease lost; refresh again')

    def assert_lease(self, lease):
        with self._db() as db:
            self._check_lease(db,lease)

    @asynccontextmanager
    async def reconciliation_lock(self, namespace, inbox):
        owner = uuid.uuid4().hex
        lease = None
        renewer = None
        lost = False
        parent = asyncio.current_task()
        try:
            while lease is None:
                fence = await asyncio.to_thread(self._try_lease,namespace,inbox,owner,30)
                if fence is not None:
                    lease = MailboxLease(namespace,inbox,owner,fence)
                else:
                    await asyncio.sleep(.25)
            async def renew():
                nonlocal lost
                try:
                    while True:
                        await asyncio.sleep(10)
                        if not await asyncio.to_thread(self._renew_lease,lease,30):
                            raise UIDStoreError('Mailbox coordination lease lost')
                except asyncio.CancelledError:
                    raise
                except Exception:
                    lost = True
                    parent.cancel()
            renewer = asyncio.create_task(renew())
            yield lease
        except asyncio.CancelledError:
            if lost: raise UIDStoreError('Mailbox coordination renewal failed; prior view retained') from None
            raise
        finally:
            if renewer:
                renewer.cancel()
                await asyncio.gather(renewer,return_exceptions=True)
            if lease:
                try:
                    await asyncio.to_thread(self._release_lease,lease)
                except UIDStoreError:
                    pass  # A failed release expires naturally after 30 seconds.

    async def reserve_request(self, credential_hash, rate):
        credential_hash = credential_hash.hex() if isinstance(credential_hash,bytes) else credential_hash
        if len(credential_hash)!=64 or any(c not in '0123456789abcdef' for c in credential_hash):
            raise UIDStoreError('A SHA256 credential fingerprint is required')
        if rate <= 0: raise UIDStoreError('Invalid request rate')
        def reserve():
            with self._db() as db:
                db.execute('INSERT INTO request_budgets(credential_hash) VALUES (%s) ON CONFLICT DO NOTHING',(credential_hash,))
                row = db.execute('SELECT EXTRACT(EPOCH FROM GREATEST(next_request,cooldown_until)-clock_timestamp()) FROM request_budgets WHERE credential_hash=%s FOR UPDATE',(credential_hash,)).fetchone()
                delay = max(0,float(row[0]))
                if delay == 0:
                    db.execute("UPDATE request_budgets SET next_request=clock_timestamp()+(%s * interval '1 second') WHERE credential_hash=%s",(1/rate,credential_hash))
                return delay
        return await asyncio.to_thread(reserve)

    async def cool_down(self, credential_hash, seconds):
        credential_hash = credential_hash.hex() if isinstance(credential_hash,bytes) else credential_hash
        if len(credential_hash)!=64 or any(c not in '0123456789abcdef' for c in credential_hash):
            raise UIDStoreError('A SHA256 credential fingerprint is required')
        def update():
            with self._db() as db:
                db.execute('INSERT INTO request_budgets(credential_hash,cooldown_until) VALUES (%s,clock_timestamp()+(%s * interval \'1 second\')) ON CONFLICT(credential_hash) DO UPDATE SET cooldown_until=GREATEST(request_budgets.cooldown_until,excluded.cooldown_until)',(credential_hash,max(0,seconds)))
        await asyncio.to_thread(update)

    async def cooldown_delay(self, credential_hash):
        credential_hash = credential_hash.hex() if isinstance(credential_hash,bytes) else credential_hash
        def read():
            with self._db() as db:
                row = db.execute('SELECT EXTRACT(EPOCH FROM cooldown_until-clock_timestamp()) FROM request_budgets WHERE credential_hash=%s',(credential_hash,)).fetchone()
                return max(0,float(row[0])) if row else 0
        return await asyncio.to_thread(read)

    def database_time(self):
        with self._db() as db:
            return float(db.execute('SELECT EXTRACT(EPOCH FROM clock_timestamp())').fetchone()[0])

    def check_ready(self):
        with self._db() as db:
            return db.execute("SELECT value FROM settings WHERE name='schema_version'").fetchone() == (2,)

    def read_snapshot(self, namespace, inbox, credential_hash, *, since):
        credential_hash = credential_hash.hex() if isinstance(credential_hash,bytes) else credential_hash
        with self._db() as db:
            row = db.execute('SELECT payload FROM mailbox_snapshots WHERE namespace=%s AND inbox=%s AND credential_hash=%s AND created_at>=to_timestamp(%s)',(namespace,inbox,credential_hash,since)).fetchone()
            if not row: return None
            data = row[0]
            return data['validity'],data['next_uid'],[Message(message_id=m['id'],uid=m['uid'],labels=m['labels'],timestamp=datetime.fromisoformat(m['timestamp']),size=m['size']) for m in data['messages']]

    def write_snapshot(self, namespace, inbox, credential_hash, result, *, lease=None):
        credential_hash = credential_hash.hex() if isinstance(credential_hash,bytes) else credential_hash
        validity,next_uid,messages = result
        payload = json.dumps({'validity':validity,'next_uid':next_uid,'messages':[{'id':m.message_id,'uid':m.uid,'labels':m.labels,'timestamp':m.timestamp.isoformat(),'size':m.size} for m in messages]})
        with self._db() as db:
            self._check_lease(db,lease)
            db.execute('DELETE FROM mailbox_snapshots WHERE created_at<clock_timestamp()-interval \'5 minutes\'')
            db.execute('INSERT INTO mailbox_snapshots(namespace,inbox,credential_hash,payload) VALUES (%s,%s,%s,%s::jsonb) ON CONFLICT(namespace,inbox,credential_hash) DO UPDATE SET payload=excluded.payload,created_at=clock_timestamp()',(namespace,inbox,credential_hash,payload))

    def invalidate_snapshot(self, namespace, inbox, *, lease=None):
        with self._db() as db:
            self._check_lease(db,lease)
            db.execute('UPDATE mailboxes SET revision=revision+1 WHERE namespace=%s AND inbox=%s',(namespace,inbox))
            db.execute('DELETE FROM mailbox_snapshots WHERE namespace=%s AND inbox=%s',(namespace,inbox))

    def reset_generation(self, previous_uidvalidity):
        if type(previous_uidvalidity) is not int or not 0 < previous_uidvalidity < MAX_UID:
            raise UIDStoreError('A known previous UIDVALIDITY below the maximum is required')
        with self._db() as db:
            db.execute('LOCK TABLE settings,mailboxes,message_uids IN ACCESS EXCLUSIVE MODE')
            current = db.execute("SELECT value FROM settings WHERE name='generation'").fetchone()[0]
            highest = db.execute('SELECT COALESCE(MAX(uidvalidity),0) FROM mailboxes').fetchone()[0]
            generation = max(previous_uidvalidity,current,highest)+1
            if generation > MAX_UID: raise UIDStoreError('UIDVALIDITY exhausted')
            db.execute('DELETE FROM message_uids')
            db.execute('DELETE FROM mailboxes')
            db.execute("UPDATE settings SET value=%s WHERE name='generation'",(generation,))
            return generation

    def backup(self,destination):
        raise UIDStoreError('Use RDS snapshots or pg_dump for PostgreSQL backup')

    def close(self):
        self.pool.close()
